version: "3.8"

services:
  api:
    build: .
    container_name: mi_api
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/testdb
    volumes:
      - .:/app
    command: npm run dev

  mongo:
    image: mongo
    container_name: mi_mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
